# Site settings
title: Sonja Förster
email: s.c.forster@umail.leidenuniv.nl
description: Sonja's personal website
baseurl: "/sf" # the subpath of your site, e.g. /blog
url: "https://sonjafoerster.github.io" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source: 

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
